"""create departments table

Revision ID: 42436e9a33e6
Revises: 32892b4a235a
Create Date: 2023-06-06 12:39:59.565923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42436e9a33e6'
down_revision = '32892b4a235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
