"""add deptartment_id

Revision ID: 5d56e398f358
Revises: 55ea202330e6
Create Date: 2023-06-06 13:21:25.768566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d56e398f358'
down_revision = '55ea202330e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
