"""add dept_id to students

Revision ID: d2be3a7e0afb
Revises: 42436e9a33e6
Create Date: 2023-06-06 12:44:48.066564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2be3a7e0afb'
down_revision = '42436e9a33e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['dept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
