"""rename departments table

Revision ID: d5c67ca932a2
Revises: d2be3a7e0afb
Create Date: 2023-06-06 13:06:39.084540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c67ca932a2'
down_revision = 'd2be3a7e0afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('departments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_dept_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['dept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_dept_id_fkey', 'departments', ['dept_id'], ['id'])

    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='departments_pkey')
    )
    op.drop_table('department')
    # ### end Alembic commands ###
